# Basic
title: cqjackeylove
subtitle: 从0-0的CTFer
welcome_message: Welcome
description: 天选也是唯一
creator: <a href="https://cqjackeylove.github.io">@cqjackeylove</a>

url: "https://github.com/cqjackeylove/cqjackeylove.github.com"

permalink: /:year/:month/:title/


highlighter: rouge


cover_color: red


blog_button:
    title: Blog
    description: Visit blog


nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/cqjackeylove'}
  

plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    
    github: cqjackeylove
  
  
    mail: 2668068433@qq.com

ga:
    # id: your_ga_id
    # host: your_host
